TOKEN_INT = "int" 
TOKEN_CLASS = "class" 
TOKEN_CONSTRUCTOR = "constructor" 
TOKEN_FUNCTION = "function" 
TOKEN_METHOD = "method" 
TOKEN_FIELD = "field" 
TOKEN_STATIC = "static" 
TOKEN_VAR = "var" 
TOKEN_CHAR = "char" 
TOKEN_BOOLEAN = "boolean" 
TOKEN_VOID = "void" 
TOKEN_TRUE = "true" 
TOKEN_FALSE = "false" 
TOKEN_NULL = "null" 
TOKEN_THIS = "this" 
TOKEN_LET = "let" 
TOKEN_DO = "do" 
TOKEN_IF = "if" 
TOKEN_ELSE = "else" 
TOKEN_WHILE = "while" 
TOKEN_RETURN = "return" 
TOKEN_IDENT  = "identifier"
TOKEN_EQ       = "="
TOKEN_EOF     = "EOF"



# Operators
TOKEN_ASSIGN   = "="
TOKEN_PLUS     = "+"
TOKEN_MINUS    = "-"
TOKEN_ASTERISK = "*"
TOKEN_SLASH    = "/"
TOKEN_AND      = "&"
TOKEN_OR       = "|"
TOKEN_NOT      = "~"
TOKEN_DOT      = "."
TOKEN_LT       = "<"
TOKEN_GT       = ">"
TOKEN_EQ       = "="
